name: Test with FMOD Sound Disabled

on: push

jobs:
  test_without_fmod:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Patch FMOD to disable sound
        run: |
          sed -i'' \
          's/result = coreSystem.setOutput(outputType);/result = coreSystem.setOutput(FMOD.OUTPUTTYPE.NOSOUND);/' \
          Assets/Plugins/FMOD/src/RuntimeManager.cs

      - name: Run tests
        uses: game-ci/unity-test-runner@main
        env:
          # gh secret set UNITY_LICENSE < /Library/Application\ Support/Unity/Unity_lic.ulf
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: Test results
          path: artifacts
